spring.application.name=Spring-Security
spring.datasource.url=jdbc:mysql://localhost:3306/spring-security?useSSl=false
spring.datasource.username=root
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Spring configuration
#spring.security.user.name=sweta
#spring.security.user.password=pass

jwt.secretKey=anshsjmdnslkxmsmnnsmnsncdncdncncxkmsamssmsmsmmsssdscdcdwwcf
deploy.env=development
